version: "3.8"

services:
  gusmelfordbooks:
    image: gusmelford_books
    container_name: gusmelfordbooks
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://$GUSMELFORDBOT_HOST:5432/app.gusmelfordbooks.java.db
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update